### ISSUE TITLE
fix "modelPath" not found nullpointer exception in case of finishing a collaboration session

### ISSUE THREAD

**Issue by 1forintos** [FTSRG/mondo-collab-framework#12]
org.json.JSONException: JSONObject["modelPath"] not found.
	at org.json.JSONObject.get(JSONObject.java:454)
	at org.json.JSONObject.getString(JSONObject.java:635)
	at org.mondo.collaboration.online.emfhandler.rest.OnlineResource.persistModel(OnlineResource.java:207)

**Comment by istvanrath** [comment]
Can you describe how to reproduce this issue?
