### ISSUE TITLE
Improve error handling and logging

### ISSUE THREAD

**Issue by istvanrath** [FTSRG/mondo-collab-framework#14]
* currently, lens.log, pre-*.log, post-*.log are not appended, but overwritten after each operation. This should be changed to an append policy.
```
$ cat lens.log
2015-10-11_23-42-58 /home/mondo/MONDO-Demo/lens/eclipse/MondoOfflineCollaborationLens -nosplash -consoleLog --launcher.suppressErrors -application org.mondo.collaboration.security.lens.offline.cli -gold /home/mondo/MONDO-Demo/example/tempGold/svn/gold/test.project.with.model.project/example.wtspec4m -front /home/mondo/MONDO-Demo/example/tempFront/Current/svn/front1/test.project.with.model.project/example.wtspec4m -macl /home/mondo/MONDO-Demo/admin/workspace/test.project.rules/src/es/ikerlan/wt/emf/security/example/rules.macl -eiq /home/mondo/MONDO-Demo/admin/workspace/test.project.rules/src/es/ikerlan/wt/emf/security/example/queries.eiq -userName alice -performPutback -configuration /home/mondo/MONDO-Demo/example -data /home/mondo/MONDO-Demo/example -obfuscatorSalt seed_/svn/front1 -obfuscatorSeed salt_/svn/front1 -obfuscatorPrefix mondo
2015-10-11_23-43-02 13
2015-10-11_23-43-02 
```
```
$ cat pre-commit.log 
2015-10-11_23-42-58 Checkout gold - from http://localhost/svn/gold to /home/mondo/MONDO-Demo/example/tempGold/svn/gold
2015-10-11_23-42-58 Get change list
2015-10-11_23-42-58 Get commit message
2015-10-11_23-42-58 Start iterating over the changes
2015-10-11_23-42-58      -> Change: U test.project.with.model.project/example.wtspec4m
2015-10-11_23-42-58      -> Action: Copy Content /home/mondo/MONDO-Demo/example/tempFront/Current/svn/front1/test.project.with.model.project/example.wtspec4m
2015-10-11_23-42-58      -> Action: Execute lens /home/mondo/MONDO-Demo/example/tempFront/Current/svn/front1/test.project.with.model.project/example.wtspec4m
2015-10-11_23-42-58 Obfuscator seed_/svn/front1 salt_/svn/front1 mondo
2015-10-11_23-43-02 Step into the gold folder
2015-10-11_23-43-02 Add changes to SVN
2015-10-11_23-43-02 Store commit message
2015-10-11_23-43-02 Commit changes to the gold
2015-10-11_23-43-02 Remove temporary files
2015-10-11_23-43-02 Pre-commit finished successfully
```

* if the lens fails for some reason, the offline collaboration framework can get into an inconsistent state (e.g. because of an ID uniqueness violation). this should be avoided.
```
!ENTRY org.eclipse.osgi 4 0 2015-10-11 20:54:28.402
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Error establishing correspondence in GOLD model :  unique key es.ikerlan.WTSpec4M.WTElement:null associated with 2 values [Ljava.lang.Object;@161b799
	at org.mondo.collaboration.security.lens.correspondence.EObjectCorrespondence.checkIndexBucket(EObjectCorrespondence.java:107)
	at org.mondo.collaboration.security.lens.correspondence.EObjectCorrespondence.buildEObjectCorrespondenceTable(EObjectCorrespondence.java:90)
	at org.mondo.collaboration.security.lens.bx.OfflineCollaborationSession.setupLens(OfflineCollaborationSession.java:113)
	at org.mondo.collaboration.security.lens.bx.OfflineCollaborationSession.<init>(OfflineCollaborationSession.java:85)
	at org.mondo.collaboration.security.lens.offline.cli.OfflineLensApplication.start(OfflineLensApplication.java:79)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608
```

**Comment by bergmanngabor** [comment]
Logging now happens through log4j.
Levels:
- DEBUG for each rule execution
- INFO for lens execution progress  "lens transformation started", etc.
- WARNING for rejected writes (this is still normal operation!) + message is nicely propagated back to client 
- ERROR and above for serious problems, possibly bugs or misconfiguration.
